spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: 'jdbc:mysql://xempre.com:3306/gamingworld_aos'
        username: external
        password: XempreDB
        driver-class-name: com.mysql.cj.jdbc.Driver
    cors:
        origins:
            - http://localhost:4200
            - https://app.mydomainnnn.com
            - https://app.yourrrrdooomain.com