spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: 'jdbc:mysql://127.0.0.1:3306/GamerWorld'
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver